
# Author:
#   Yuanqing Wu, KAUST, Saudi Arabia
#
# History:
#   2017-2-9 by Yuanqing Wu
#
# Support:
#   wuyuanq@gmail.com

PROG = sg
defaults: ${PROG}

FCC = gfortran
#FCC = mpif90

FCFLAGS = -O3 -fdefault-real-8 -g
FCFLAGS = -g -fdefault-integer-8
#FCFLAGS = -O3 -fbounds-check
#FCFLAGS = -fcheck=all -g

TRUETYPE = FLASH
TRUETYPE = NN

ifeq ($(TRUETYPE), FLASH)
TRUEFLAGS = -DFLASH
else ifeq ($(TRUETYPE), NN)
TRUEFLAGS = -DNN
endif

vpath RST_getEquResidual.F90 ../../DeepLearning
VPATH = ../../FlashCalculation

ifeq ($(TRUETYPE), FLASH)
TRUESRCS = RST_globalFlashData.F90 RST_mathlib.F90 RST_PREOS.F90 RST_comprefac.F90 \
RST_fugacitycoef.F90 RST_stability.F90 RST_pmv.F90 RST_flashcalculation.F90 RST_viscosity.F90
else ifeq ($(TRUETYPE), NN)
TRUESRCS = RST_globalFlashData.F90 RST_mathlib.F90 RST_PREOS.F90 \
RST_fugacitycoef.F90 RST_getEquResidual.F90
endif

FSRCS = RST_globalSgData.F90 RST_hashTable.F90 RST_sg.F90 infile_sg.F90
      
%.o: %.F90
	$(FCC) -c $(TRUEFLAGS) $(FCFLAGS) $^ -o $@

TRUEOBJS = $(TRUESRCS:.F90=.o)
FOBJS = $(FSRCS:.F90=.o)

$(PROG): $(TRUEOBJS) $(FOBJS)
	$(FCC) $(TRUEFLAGS) $(FCFLAGS) $(TRUEOBJS) $(FOBJS) -o $(PROG)

all: $(PROG)

.PHONY: clean

clean:
	rm -rf *.mod *.o *.dSYM *.asv $(PROG)

run: ${PROG} 
#	mpirun -np 1 ./${PROG}
	./${PROG}

